### ISSUE TITLE
"Show Diff" popup too narrow

### ISSUE THREAD

**Issue by gruppler** [qzchenwl/git-change-marker#1]
When I initially click the "Show Diff" button, the popup appears correctly for an instant, then immediately becomes very narrow, wrapped to the width of the buttons.

![bug](https://cloud.githubusercontent.com/assets/301190/16512591/fa259544-3f2a-11e6-949b-22d52483fb5b.png)

Setting `atom-overlay`'s width to `100%` seems to solve the problem.

**Comment by qzchenwl** [comment]
@gruppler I cannot reproduce it. What's your atom version?

Here's mine:

``` bash
~ $ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by gruppler** [comment]
My Atom version is the same. It seems possible that another package is conflicting somehow.

If I disable absolute positioning of the `atom-overlay` I think I can see where it's getting its width:

![bug](https://cloud.githubusercontent.com/assets/301190/16513165/5e05d34e-3f30-11e6-8c4b-fce5ab43f500.png)

**Comment by airtonix** [comment]
@gruppler can you paste in the exact less you're implementing to fix this?

nvm... I discovered this works:

``` less
// ~/.atom/styles.less
atom-overlay atom-text-editor:not([hidden]){
    min-width: 60vw;
}
```

**Comment by qzchenwl** [comment]
@gruppler @airtonix , after some update, I can reproduce it. It's now fixed. :-)

**Comment by gruppler** [comment]
Unfortunately, this didn't solve the issue for me.

I'm seeing the overlay initially open to 100% width (which also makes the editor window show a horizontal scrollbar because it's **too** wide now), but only for a few milliseconds. It immediately gets resized to the same narrow width, but it doesn't look like it's getting a specific width. Looking at the debugger and stepping through all the relevant elements, I see none of them has a specific height set. That seems to suggest the problem might have more to do with where in the dom the overlay is inserted.

![toowide](https://cloud.githubusercontent.com/assets/301190/17639851/ad4547cc-60c4-11e6-8fbf-aafeddb05cd1.png)
...and them immediately...
![toowide2](https://cloud.githubusercontent.com/assets/301190/17639852/b1967b66-60c4-11e6-86cf-443b80fc8bcf.png)

**Comment by gruppler** [comment]
The solution suggested by @airtonix doesn't work if you're using a split window. The same overflow problem occurs. However, I'm not getting the immediate resizing back to a narrow width.

**Comment by dmig** [comment]
Just faced this issue with atom 1.21.0-beta1.
I suggest this fix:
```less
.git-change-marker-toolbar {
  // ...
  atom-text-editor {
    min-width: 60vw; // <-- add this
    .lines > div > div {
        position: static !important;
    }
  }
}
```
Also I'd limit editor height to e.g. 50% of viewport for large changes, because now it's end is going out of screen.
